### ISSUE TITLE
"getPrefLabel is not a function"

### ISSUE THREAD

**Issue by pmackay** [nichtich/wikidata-taxonomy#29]
I get this output running `wdtaxonomy -f csv Q634` on node `v9.1.0`. It works fine on `v6.10.0`.

**Comment by nichtich** [comment]
Sorry, this is a bug introduced in 0.5.1, now fixed in 0.5.2
